### ISSUE TITLE
建议在web页面中增加一个启动/停止的开关

### ISSUE THREAD

**Issue by RichardDon** [jm33-m0/hiwifi_scripts#2]
web页面中没有开关。建议增加一个启动/停止的开关，这样控制起来就更方便了。停止的时候最好能同时把自定义host给关闭，这样感觉非常的完整。

**Comment by jm33-m0** [comment]
我不明白为什么你需要停止。。而且自定义hosts解决了你上千个域名的DNS污染问题，更没有道理去还原它。

这么说吧，你用国内外分流模式的时候这个代理就已经可以认为是透明的了，需要关闭它的情况几乎不存在。（讲道理之前geewan写这个插件的时候是有开关的，我觉得没用就去掉了）

**Comment by jm33-m0** [comment]
自定义hosts我还没有做好自动更新，如果可以正常更新的话我会在README通知。另，我还会做一个利用socks通道转发DNS请求的功能（dns2socks）来彻底解决DNS污染

**Comment by RichardDon** [comment]
没想到回复这么快，呵呵。

说一下原因。我在mac上用了surge for mac。之前一直在用geewan的路由器插件。但是发现有时候插件偶尔会连接失败，导致无法翻墙。这个时候，我一般用surge for mac来解决。

今天发现，但是今天发现，我在路由器上，运行了hosts.sh命令后，surge for mac 无法正常使用了。想调试下，关闭这个插件，简单判断下是否是因为使用了hosts.sh的问题导致 surge for mac无法使用，但是没找到按钮，想看看你这边是否可以考虑增加这个按钮。

基本原因就是以上遇到的。因为时间关系，我就没有去做网络调试的工作来查找更细节的情况，以上的反馈还是比较粗，望谅解。

**Comment by jm33-m0** [comment]
mac上完全可以用Python版本的shadowsocks，不需要第三方的解决方案。你说的无法使用请具体说明，可以更换网络排查问题，从我的角度看，你修改hosts完全不会影响ss的工作，因为ss只是转发流量而已，除非hosts是错的完全不能用

**Comment by jm33-m0** [comment]
可以在我博客找到联系方式

**Comment by ukid** [comment]
我觉得开关有存在的必要性，比如VPS流量不够需要临时关闭，再比如淘宝有个规则，如果能访问被墙的资源，则跳转到淘宝海外版

**Comment by ukid** [comment]
我觉得最需要修改的是初始化时只能上传配置文件，不能直接通过form配置

**Comment by ukid** [comment]
如果各种功能都能通过页面配置就更好了，让用户自由选择

**Comment by jm33-m0** [comment]
这个插件是从geewan那里改写过来的，最初的目的只是让老版本的插件能够在更换界面之后的极路由固件上使用以及升级shadowsocks本身。所以除了使用界面的适配和DNS防污染之外没有做别的工作。
有空的话我会考虑做更多改进，或者把shadowsocks luci版本移植过来

**Comment by RichardDon** [comment]
很期待继续改进，我们可以帮忙测试。

**Comment by RichardDon** [comment]
貌似没看到代码更新。。。下载了最新版，还没看到开关。

**Comment by jm33-m0** [comment]
还没有更新。。
